# Generated by Django 5.1.6 on 2025-03-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Bad', 'Bad')], max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
